spring:
  application:
    name: sg-tavern
  datasource:
    url:
    username:
    password:
  jpa:
    hibernate:
      ddl-auto:
      naming.physical-strategy:
    show-sql:
    properties:
      hibernate:
        dialect:
    open-in-view:
discord.bot.token:

guildId:

userId:
  owner:
  dev:
  bot:

channelId:
  intro:
  rules:
  admin-bot:
  upcoming-event:

private:
  channels:
    -
  threads:
    -

roleId:
  event-organiser:
  new-joiner:
  name-colour-anchor: