spring:
  application:
    name: sg-tavern
  datasource:
    url:
    username:
    password:
  jpa:
    hibernate:
      ddl-auto:
      naming.physical-strategy:
    show-sql:
    properties:
      hibernate:
        dialect:
    open-in-view:

discord.bot.token:
gpt.apiKey:

guildId:

userId:
  owner:
  dev:
  bot:

channelId:
  intro:
  rules:
  admin-bot:
  moderator-only:
  admin-chat:
  admin-it-chat:
  upcoming-event:
  events-promo:

private-channels:
  -
private-threads:
  -

roleId:
  event-organiser:
  new-joiner:
  name-colour-anchor:

post:
  event-template: